### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by MrTyton** [resetes12/pokeemerald#51]
Hi,

I'm trying to build this, and am getting a compilation error.
```
make modern
/opt/devkitpro/devkitARM/bin/../libexec/gcc/arm-none-eabi/15.1.0/cc1 -quiet <flags> -o build/modern/src/event_object_movement.o src/event_object_movement.c
src/event_object_movement.c: In function 'GetFollowerInfo':
src/event_object_movement.c:2208:9: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
 2208 |         return;
      |         ^~~~~~
src/event_object_movement.c:2203:14: note: declared here
 2203 | static bool8 GetFollowerInfo(u16 *species, u8 *form, u8 *shiny)
      |              ^~~~~~~~~~~~~~~
make: *** [Makefile:340: build/modern/src/event_object_movement.o] Error 1
make: *** Deleting file 'build/modern/src/event_object_movement.o'
```

Following the compilation instructions and using `git clone https://github.com/resetes12/pokeemerald` as the source.

Any idea how to fix?

**Comment by friendlymammal** [comment]
I ran into a similar issue when trying to compile the latest version just now. Here are some extra details about the triggering conditions and my attempted fixes, in case it's helpful:

**Description**
Getting compilation error(s) when trying to build with `make modern`. 

**Error** 
<details> 

<summary>Pretty much the same as OP, but included just in case</summary>

```
src/event_object_movement.c: In function 'GetFollowerInfo':
src/event_object_movement.c:2208:9: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
 2208 |         return;
      |         ^~~~~~
src/event_object_movement.c:2203:14: note: declared here
 2203 | static bool8 GetFollowerInfo(u16 *species, u8 *form, u8 *shiny)
      |              ^~~~~~~~~~~~~~~
make: *** [Makefile:340: build/modern/src/event_object_movement.o] Error 1
make: *** Deleting file 'build/modern/src/event_object_movement.o'
```

</details>

**My setup**
- Operating System: Linux Mint 22.1 Cinnamon
- Compiler: arm-none-eabi-gcc (15:13.2.rel1-2) 13.2.1 20231009
- Git commit: 54c0e5e49514964323c768a6398add9ee6aff42d

**What I Did**
1. Cloned the repository
2. Renamed a clean copy of Pokemon Emerald (USA) to ```baserom.gba``` and put it in the root directory
3. Ran `make clean`
4. Ran `make modern`
5. Got this error, assumed I did something wrong, so started from scratch and did it again with the same result :c 
6. Attempted a fix, then got a different (related?) compilation error. Details below:

**Other relevant info**
I'm very much a newb when it comes to ROM hacks and incredibly rusty with C, so please take all of this with a lot of salt! If I'm reading it right, the ```GetFollowerInfo``` function is supposed to return a boolean, but the ```else``` statement doesn't seem to provide one on line 2208. 
The function in question:
<details> 

<summary>GetFollowerInfo</summary>

```
static bool8 GetFollowerInfo(u16 *species, u8 *form, u8 *shiny)
{
    if (gSaveBlock2Ptr->optionsfollowerEnable == 0)
        return GetMonInfo(GetFirstLiveMon(), species, form, shiny);
    else
        return;
}
```

</details>

**Attempted fix + related issues?**
I tried changing line 2208 to ```return FALSE;``` and it seemed to fix the first compilation error. I still wasn't able to compile though-- This time, it returned another compilation error in  `src/field_player_avatar.c`:
<details> 

<summary>MovementType_Player error</summary>

```
src/field_player_avatar.c: In function 'MovementType_Player':
src/field_player_avatar.c:327:79: error: passing argument 3 of 'UpdateObjectEventCurrentMovement' from incompatible pointer type [-Wincompatible-point
er-types]
  327 |     UpdateObjectEventCurrentMovement(&gObjectEvents[sprite->data[0]], sprite, ObjectEventCB2_NoMovement2);
      |                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                               |
      |                                                                               u8 (*)(void) {aka unsigned char (*)(void)}
In file included from src/field_player_avatar.c:5:
include/event_object_movement.h:159:78: note: expected 'bool8 (*)(struct ObjectEvent *, struct Sprite *)' {aka 'unsigned char (*)(struct ObjectEvent *, struct Sprite *)'} but argument is of type 'u8 (*)(void)' {aka 'unsigned char (*)(void)'}
  159 | void UpdateObjectEventCurrentMovement(struct ObjectEvent *, struct Sprite *, bool8(struct ObjectEvent *, struct Sprite *));
      |                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/field_player_avatar.c:44:11: note: 'ObjectEventCB2_NoMovement2' declared here
   44 | static u8 ObjectEventCB2_NoMovement2();
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:340: build/modern/src/field_player_avatar.o] Error 1
make: *** Deleting file 'build/modern/src/field_player_avatar.o'
```

</details>

I'm guessing the issues are related, since they both involve follower/object event functionality, but I'm in way over my head... I hope any of this is helpful!

**Comment by resetes12** [comment]
I'm also stumped, but maybe I'm the one mistaken, thinking I haven't done extra steps when installing my repository.

Maybe try [re-installing agbcc to the project](https://github.com/pret/pokeemerald/blob/master/INSTALL.md#installation), although I don't know if this affects modern builds though.
Also try` make clean-tools`, or[ this to supposedly install devkitARM to use the modern compiler.](https://github.com/pret/pokeemerald/blob/master/INSTALL.md#devkitarms-c-compiler)

Besides that, `arm-none-eabi-gcc --version` returns that it hasn't been installed on my machine, and I don't know where to look for  `make modern V=1 2>&1 | head -20 `and `make V=1 2>&1 | head -10` outputs.

As you can see, I'm not very well-versed in this kind of stuff, but I'm willing to try whatever you guys need in order to help you.

**Comment by TixoRebel** [comment]
Could you try running `/opt/devkitpro/devkitARM/bin/arm-none-eabi-gcc --version`? Unfortunately I am already using `devkitARM` from that link.

**Comment by resetes12** [comment]
Sure, that one works.
`arm-none-eabi-gcc (devkitARM release 62) 13.2.0`

**Comment by friendlymammal** [comment]
Thanks for being willing to troubleshoot! Honestly, I'm not very well versed either, so I'm learning as I go.  

There are 3 details about your setup that would be helpful to know, whenever you have a chance to open up VSCode and try some commands. You'd run all 3 of these in the terminal, same as if you were running a `make modern` command. 

1. `gcc --version` should tell us which version of GCC you're using
2. `lsb_release -a` will tell us information about your Ubuntu install. 
3. `make modern V=1 2>&1 | head -20` will tell us more details about the compiler commands and flags being used when you run `make modern`


I've reinstalled agbcc and confirmed I'm working with devkitARM. You're on a slightly older version than the ones I've tried -- I've used 13.2.1 and 15.1.0 so far. I'll try 13.2.0 soon! (If you're curious and want more info on the commands Tixo and I asked about, I've stuck some info in the spoiler). 
<details>
<summary>checking devkitARM versions</summary>

- The command that TixoRebel suggested `/opt/devkitpro/devkitARM/bin/arm-none-eabi-gcc --version`  is a way to check which version of devkitARM you're using. You've got an older version (release 62, rather than 66). 
- The command that I suggested was asking for the same information, but it didn't work because `arm-none-eabi-gcc` isn't in your PATH. In other words, it's installed, but the terminal only knows how to handle it using the longer name that TixoRebel used.
</details>

**Comment by resetes12** [comment]
> The problem seems to be that version 66 of devkitARM updated to a GCC version which defaulted to c23, which gets rid of a bunch of old features / undefined behavior in the language that this repo relies on. I opened a pull request ([#52](https://github.com/resetes12/pokeemerald/pull/52)) to resolve some of these issues and allow this repo to compile with version 65 of devkitARM, which defaults to c17, but some more changes would be required to use c23.

I finally merged #52. If you are willing to continue fixing these issues, I'll try to merge them whenever I have some time.

**Comment by resetes12** [comment]
Sure, go ahead.

**Comment by iball** [comment]
> > I take it this hasn't been resolved yet?
> > /usr/lib/gcc/arm-none-eabi/10.3.1/cc1 -quiet -o build/modern/src/field_player_avatar.o src/field_player_avatar.c src/field_player_avatar.c: In function 'ObjectEventCB2_NoMovement2': src/field_player_avatar.c:362:38: error: parameter name omitted 362 | static u8 ObjectEventCB2_NoMovement2(struct ObjectEvent *, struct Sprite *) | ^~~~~~~~~~~~~~~~~~~~ src/field_player_avatar.c:362:60: error: parameter name omitted 362 | static u8 ObjectEventCB2_NoMovement2(struct ObjectEvent *, struct Sprite *) | ^~~~~~~~~~~~~~~ make: *** [Makefile:340: build/modern/src/field_player_avatar.o] Error 1 make: *** Deleting file 'build/modern/src/field_player_avatar.o'
> 
> I don't know. People have fixed a couple of issues here and there, but I've never had compiling problems with version 62 to begin with.
> 
> The rule is, if you're compiling and it happens, then it hasn't. It's best to use version 62 of the GCC compiler (the one I'm using and i'll continue using) or 65, which _should_ have most issues fixed. Higher versions will require manual fixing from the user.

Figured it out.  My dev platform was running an older release of Ubuntu.  
Once I did an in-place upgrade to the latest Ubuntu, it compiled just fine after that.  Doh!

**Comment by friendlymammal** [comment]
Hi folks! Came back to tinkering with this after a few months and was able to resolve the issue after finding Leseratte's archive of [old versions of devkitpro](https://wii.leseratte10.de/devkitPro/). This is my first time modding a ROM hack, so it took me a while to figure out how to get back to release 62 😅 If it's helpful to any other new folks, these are the steps that I took to make it work on **Linux Mint 22.3 Cinnamon**. I followed these steps after installing agbcc from pret's instructions. 

- Download `devkitARM-r62-1-linux_x86_64.pkg.tar.zst` from [Leseratte's archive](https://wii.leseratte10.de/devkitPro/devkitARM/r62%20%282023-08-04%29/)
- Extract the files from the zst file you just downloaded. (I put them in my Downloads in a folder called `devkitpro-temp`). 
-  In the extracted files, go to the `devkitARM` directory and change the name of the folder to `devkitARM62`. 
- Move the `devkitARM62` folder: `sudo mv devkitARM62 /opt/devkitpro/`
- In the terminal, go to the pokeemerald repo.
- Set your local environment variable to release 62: `export DEVKITARM=/opt/devkitpro/devkitARM62`
- Run `make modern` 

If you need a more recent version of devkitARM on your system for other projects, doing it this way should leave the system defaults undisturbed :) If you spot a mistake, please let me know! Still learning. If all goes well, I'll be able to report back having successfully upgraded Chimecho's moveset to match the Gen VI Hoenn remakes. 🫡
